### ISSUE TITLE
startWatcherWithAutoReload error

### ISSUE THREAD

**Issue by lostsatellites** [pattern-lab/patternlab-php#302]
I'm getting this error when startWatcherWithAutoReload.command tries to initiate the browser refresh. I'm still able to manually refresh to see changes. Any thoughts on why it stopped working?

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Invalid request line' in /Users/e159/Sites/LT-patternlab/core/lib/Wrench/Protocol/Protocol.php:724
Stack trace:
#0 /Users/e159/Sites/LT-patternlab/core/lib/Wrench/Protocol/Protocol.php(442): Wrench\Protocol\Protocol->getRequestHeaders('\x16\x03\x01\x00\xB0\x01\x00\x00\xAC\x03\x03\xC0\\\xB7\x1D...')
#1 /Users/e159/Sites/LT-patternlab/core/lib/Wrench/Connection.php(227): Wrench\Protocol\Protocol->validateRequestHandshake('\x16\x03\x01\x00\xB0\x01\x00\x00\xAC\x03\x03\xC0\\\xB7\x1D...')
#2 /Users/e159/Sites/LT-patternlab/core/lib/Wrench/Connection.php(210): Wrench\Connection->handshake('\x16\x03\x01\x00\xB0\x01\x00\x00\xAC\x03\x03\xC0\\\xB7\x1D...')
#3 /Users/e159/Sites/LT-patternlab/core/lib/Wrench/Connection.php(403): Wrench\Connection->onData('\x16\x03\x01\x00\xB0\x01\x00\x00\xAC\x03\x03\xC0\\\xB7\x1D...')
#4 /Users/e159/Sites/LT-patternlab/core/lib/Wrench/ConnectionManager.php(245): Wrench\Connection->process()
#5 /Users/e159/Sit in /Users/e159407/Sites/LT-patternlab/core/lib/Wrench/Protocol/Protocol.php on line 724

**Comment by lostsatellites** [comment]
Closing this, someone had globally changed all instances of ws:// to wss://. Apologies if this took anyone's time but my own!
