### ISSUE TITLE
"The partial could not be found" when using styleModifier

### ISSUE THREAD

**Issue by msisto** [pattern-lab/patternlab-php#385]
"The partial could not be found" when using styleModifier

I cannot seem to get `styleModifier` to work.

Here's my pattern at `/source/_patterns/atoms/button.hbs`:

```
<button class="c-button {{ styleModifier }}">
  Button
</button>
```

and the modified button at `/source/_patterns/atoms/confirm-button.hbs`:

```
{{> atoms-button:confirm }}
```

I am expecting this output:

```
<button class="c-button confirm">
  Button
</button>
```

But am receiving this compilation error:

```
Built pattern: atoms-button
[13:20:26] 'build' errored after 167 ms
[13:20:26] Error: The partial atoms-button:confirm could not be found
    at Object.invokePartial (/Users/matt.sisto/src/pattern-lab/node_modules/patternengine-node-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:271:11)
    at Object.invokePartialWrapper [as invokePartial] (/Users/matt.sisto/src/pattern-lab/node_modules/patternengine-node-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at Object.eval (eval at createFunctionContext (/Users/matt.sisto/src/pattern-lab/node_modules/patternengine-node-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/Users/matt.sisto/src/pattern-lab/node_modules/patternengine-node-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/Users/matt.sisto/src/pattern-lab/node_modules/patternengine-node-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/Users/matt.sisto/src/pattern-lab/node_modules/patternengine-node-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at Object.renderPattern (/Users/matt.sisto/src/pattern-lab/node_modules/patternengine-node-handlebars/lib/engine_handlebars.js:56:12)
    at Object.Pattern.render (/Users/matt.sisto/src/pattern-lab/node_modules/patternlab-node/core/lib/object_factory.js:101:26)
    at renderPattern (/Users/matt.sisto/src/pattern-lab/node_modules/patternlab-node/core/lib/pattern_assembler.js:145:22)
    at Object.forEach.patternlab.renderPattern (/Users/matt.sisto/src/pattern-lab/node_modules/patternlab-node/core/lib/pattern_assembler.js:587:14)
[13:20:26] 'patternlab:build' errored after 848 ms
[13:20:26] 'patternlab:serve' errored after 849 ms
```

I am running the Gulp version of PL, and here is the contents of `package.json`:

```
{
  "name": "edition-node-gulp",
  "description": "The gulp wrapper around patternlab-node core, providing tasks to interact with the core library and move supporting frontend assets.",
  "version": "1.3.1",
  "dependencies": {
    "browser-sync": "^2.0.0",
    "gulp": "gulpjs/gulp#4.0",
    "minimist": "^1.2.0",
    "patternlab-node": "^2.8.0",
    "styleguidekit-assets-default": "^3.0.0",
    "styleguidekit-mustache-default": "^3.0.0",
    "gulp-cssnext": "^1.0.1",
    "patternengine-node-handlebars": "^1.0.0"
  },
  "keywords": [
    "Pattern Lab",
    "Atomic Web Design",
    "Node",
    "Gulp",
    "Javascript"
  ],
  "repository": {
    "type": "git",
    "url": "git://github.com/pattern-lab/edition-node-gulp.git"
  },
  "bugs": "https://github.com/pattern-lab/edition-node-gulp/issues",
  "author": "Brian Muenzenmeyer",
  "scripts": {
    "postinstall": "node node_modules/patternlab-node/core/scripts/postinstall.js"
  },
  "license": "MIT",
  "engines": {
    "node": ">=5.0"
  },
  "devDependencies": {
    "gulp-directory-sync": "^1.2.3"
  }
}
```

Am I missing something?

**Comment by msisto** [comment]
Woops, wrong project!
